### ISSUE TITLE
[FEAT] 앨범 List Network 연결

### ISSUE THREAD

**Issue by GeonHyeongKim** [YAPP-Github/20th-iOS-Team-2-FE#108]
## 📌  Feature Issue

|![image](https://user-images.githubusercontent.com/48436020/179387421-5f7e6c1c-1ad9-424c-a184-9716777edfc3.png)|![image](https://user-images.githubusercontent.com/48436020/179387427-0ff4aa37-94b1-4246-bdb3-9e5f346d39cb.png)|
|:-:|:-:|
|날짜별|유형별|

## 📝  To-do

- [x] Network
  - [x] 날짜별, 유형별 List
  - [x] 날짜별 pagenation
- [x] refresh, pagenat UI
- [x] 아래 하단 흰색 Area 버그 
- [x] 디자인 수정(폰트, 여백 등)
