### ISSUE TITLE
[FEAT] 사진 업로드 Network

### ISSUE THREAD

**Issue by GeonHyeongKim** [YAPP-Github/20th-iOS-Team-2-FE#112]
## 📌  Feature Issue

사진 업로드 network

## 📝  To-do

- [x] Network
  - [x] 사진 앨범 선택 후 
  - [x] 카메라 사진 찍은 후
- [x] 디자인 수정(폰트, 여백 등)
