### ISSUE TITLE
[FIX] 앨범 List API 

### ISSUE THREAD

**Issue by GeonHyeongKim** [YAPP-Github/20th-iOS-Team-2-FE#118]
## 📌  Feature Issue

- 앨범 List 버그 수정

|![image](https://user-images.githubusercontent.com/48436020/180194830-aee71f6d-6065-40c8-bae7-e51ee80f1175.png)|
|:-:|
|버그|

## 📝  To-do

- [x] Photo API 수정
- [x] 이미지 받아오기(라이브러리)
- [x] refresh, pagenation 수정
- [x] 녹음일 경우, 기본 Image
