### ISSUE TITLE
[FIX] 부자연스러운 UI 해결

### ISSUE THREAD

**Issue by GeonHyeongKim** [YAPP-Github/20th-iOS-Team-2-FE#132]
## 📌  Feature Issue

부자연스러운 UI 해결

## 📝  To-do

- [x] 유형별 -> 즐겨찾기 -> 상세 화면에서 즐겨찾기 해제 후, 게시물 없애기
- [x] 업로드 후, 바로 앨범 List에 추가하기
- [x] 버벅임 및 로직 분리
