### ISSUE TITLE
[FEAT] 자동로그인 및 로그아웃

### ISSUE THREAD

**Issue by uujinn** [YAPP-Github/20th-iOS-Team-2-FE#135]
## 📌  Feature Issue

- 토큰 및 키체인 관련 기능 정리

## 📝  To-do

- [x] 로그인 시 회원등록 후 AccessToken 저장
- [x] 로그아웃 시 키체인에서 AccessToken 삭제
- [x] 앱 삭제 시 키체인에서 AccessToken 삭제
