### ISSUE TITLE
[FEAT] 대표사진 설정, 게시글 날짜 수정, acessToken header

### ISSUE THREAD

**Issue by GeonHyeongKim** [YAPP-Github/20th-iOS-Team-2-FE#151]
## 📌  Feature Issue

|![image](https://user-images.githubusercontent.com/48436020/182097380-e2526c97-63a9-4362-88fb-75ddbb741a02.png)|![image](https://user-images.githubusercontent.com/48436020/182097490-4297f59d-478b-4b59-8717-c1235047dbc0.png)|
|:-:|:-:|
|대표/날짜|위쪽 시간흰색|

## 📝  To-do

- [x] 대표 사진 설정 API
- [ ] 게시글 날짜 수정 API
- [x] 녹음, 이미지/음성 디테일 safe area 흰색으로
- [ ] API 호출시, header에 keychain에 저장된 것 사용하기(마스터 사용 x)
- [x] 각종 버그
