### ISSUE TITLE
[FEAT] 홈 API 연결

### ISSUE THREAD

**Issue by uujinn** [YAPP-Github/20th-iOS-Team-2-FE#156]
## 📌  Feature Issue

- [ ] 홈 API + 애니메이션 및 UI 대응

## 📝  To-do

- [ ] 홈 정보 조회 (개수 별 ⚠️)
- [ ] 인사하기 - 메시지
- [ ] 인사하기 - 이모지 (애니메이션 ⚠️)
- [ ] 히스토리 조회 (개수 별 ⚠️)
