### ISSUE TITLE
[CHORE] Album 나중에 해야할 일

### ISSUE THREAD

**Issue by GeonHyeongKim** [YAPP-Github/20th-iOS-Team-2-FE#17]
## 📝  To-do

- [x] [논의] [개발자] 폴더링
- [x] [논의] [디자이너] row shadow
- [x] [논의] [디자이너] 앨범 제목이 길어지면?
- [x] [논의] [기획] pull screen vs push stack
  * 추가 -> 앨범
- [x] [논의] [디자이너] 사진 추가 Loding View
- [x] [논의] [디자이너] Row의 spacing 사진 추가 View
- [x] [논의] [기획] 3개 이후 알림 메시지
- [x] [논의] [기획] 3개 이후 선택 알림 후 가능 vs 불가능
- [ ] [논의] [기획] 앨범 선택 후, 이미지들을 보여주지 않아도 되나?
- [x] [수정] Color 받아서 수정
- [x] [수정] GreyOutOfFocusView의 tabBarHight 받아서 계산
- [x] [버그] Album의 Navigation plus 버튼을 두번 click 하면 tabbar toggle이 꼬이는 문제
- [ ] [개발] 내장 앨범에서 사진을 infinite scroller 받아오기 - 현재 1000개 가져오기로 되어있음
- [x] [개발] (앨범, 카메라, 녹음) 권한 요청 거절 후, 화면 닫기
- [x] [버그] NavigationLink로 접근후, dismiss하면 navigation bar background color에 색상 오류
