### ISSUE TITLE
[FEAT] Login View UI

### ISSUE THREAD

**Issue by uujinn** [YAPP-Github/20th-iOS-Team-2-FE#18]
## 📌  Feature Issue

<img src = "https://user-images.githubusercontent.com/70887135/173189603-a078fac3-21bf-4411-886a-828563673aa8.png" width="30%" height="30%">

- [x] Login View UI 구현

## 📝  To-do

- [x] Lottie Animation (임시)
- [x] Title & Layout
- [x] 카카오 & 애플 로그인 버튼
- [x] Context
