### ISSUE TITLE
[FEAT] Album 유형별 List Row & Album Detail View

### ISSUE THREAD

**Issue by GeonHyeongKim** [YAPP-Github/20th-iOS-Team-2-FE#21]
## 📌  Feature Issue

| <img width="311" alt="스크린샷 2022-06-12 오후 2 22 23" src="https://user-images.githubusercontent.com/48436020/173217083-e2cd0858-a31d-4a37-bdf4-f18fa2d3d5bb.png"> | ![스크린샷 2022-06-12 오후 2 37 33](https://user-images.githubusercontent.com/48436020/173217305-ec161271-d7f9-4131-b5a2-9037ca41771d.png) |  <img width="309" alt="스크린샷 2022-06-12 오후 2 22 10" src="https://user-images.githubusercontent.com/48436020/173217089-7df30914-e232-4bc8-8e38-1a3b806426af.png"> |
| :-: | :-: | :-: |
| Album 유형별 List Row | 사진 올리기 (except 캘린더, only navigaion bar) | Album Detail View |

## 📝  To-do

- [x] 유형별 List Row
- [x] Album Detail Row
- [x] Album Detail List
- [x] ViewModifier - NavigationBar with text button style
- [x] 즐겨찾기 Toggle 및 댓글 표시
- [x] 사진 올리기 (except 캘린더, only navigaion bar)
