### ISSUE TITLE
[FEAT] 로그인 뷰 UI Detail

### ISSUE THREAD

**Issue by uujinn** [YAPP-Github/20th-iOS-Team-2-FE#26]
## 📌  Feature Issue

- [x] 로그인 뷰 UI 디테일 잡기

## 📝  To-do

- [x] Device 해상도 맞추기
- [x] Font 색상 다시 확인
- [x] Context multiple style 적용
