### ISSUE TITLE
[CHORE] 디자인 수정 (action sheet의 줄 추가,  shadow 제거, 제목 두줄로 표시 상단 이미지 여백)

### ISSUE THREAD

**Issue by GeonHyeongKim** [YAPP-Github/20th-iOS-Team-2-FE#28]
## 📌  Feature Issue

|<img width="80%" alt="스크린샷 2022-06-12 오후 2 22 23" src="https://user-images.githubusercontent.com/48436020/173778131-32088e07-f187-4373-be39-41758f1e15f8.png"> | !<img width="70%" alt="스크린샷 2022-06-12 오후 2 22 23" src="https://user-images.githubusercontent.com/48436020/173778296-d921e423-2c26-4099-ab27-ae068c6a4bfd.png"> |
| :-: | :-: |
| action sheet의 줄 | shadow 제거 |
| <img width="120%" alt="스크린샷 2022-06-12 오후 2 22 23" src="https://user-images.githubusercontent.com/48436020/173779327-7e0d8bd3-99d5-4644-9266-7e9a77f0173f.png"> | <img width="120%" alt="스크린샷 2022-06-12 오후 2 22 23" src="https://user-images.githubusercontent.com/48436020/173779916-e8465f1b-2f33-4859-a976-17fca04e7704.png"> |
| 제목 두줄 | 상단 이미지 여백 |

## 📝  To-do

- [x] action sheet의 줄 추가
- [x] shadow 제거
- [x] 제목 두줄로 표시
- [x] 사진 추가 선택 - 상단 이미지 여백
