### ISSUE TITLE
[FEAT] 카메라 기능와 녹음 기능

### ISSUE THREAD

**Issue by GeonHyeongKim** [YAPP-Github/20th-iOS-Team-2-FE#29]
## 📌  Feature Issue

|![image](https://user-images.githubusercontent.com/48436020/173781982-58a45753-5185-4206-b798-170567063f1d.png) | ![image](https://user-images.githubusercontent.com/48436020/173782040-7100a3df-181c-4784-bce8-e47c0713227b.png) | ![image](https://user-images.githubusercontent.com/48436020/173782094-1f783d29-ef86-42f1-bc0b-881dd0bdff28.png) |
| :-: | :-: | :-: |
| 카메라 | 녹음 전 | 녹음 중 |

## 📝  To-do

- [x] 카메라 권한 설정
  - [x] 접근 거절 후, Alert
- [x] 다음 View에 image 넘기기
- [x] 녹음 권한 설정
- [x] 녹음 전 View
- [x] 녹음 중 View
  - [x] 애니메이션
- [x] 녹음 후, 날짜 제목 생성 후 넘기기
