### ISSUE TITLE
[FEAT] Home 상단 UI

### ISSUE THREAD

**Issue by uujinn** [YAPP-Github/20th-iOS-Team-2-FE#35]
## 📌  Feature Issue

- [ ] Home 상단 UI

## 📝  To-do

- [ ] Navigation View 적용
- [ ] 일정 UI 구현
