### ISSUE TITLE
[FEAT] Toast Message

### ISSUE THREAD

**Issue by GeonHyeongKim** [YAPP-Github/20th-iOS-Team-2-FE#41]
## 📌  Feature Issue

|![image](https://user-images.githubusercontent.com/48436020/175852812-691ceb3f-57dc-44ca-bfde-1168469f187d.png)|
| :-: |
| Toast Message |

## 📝  To-do

- [x] 3초간 alert 출력
- [x] click으로 alert 제거
- [x] alert 마다 고유 색상
- [x] 적용
