### ISSUE TITLE
[FEAT] Album Detail View에서 이미지를 click 했을때 확대 View (ImageDetailView)

### ISSUE THREAD

**Issue by GeonHyeongKim** [YAPP-Github/20th-iOS-Team-2-FE#46]
## 📌  Feature Issue

|![image](https://user-images.githubusercontent.com/48436020/176079582-4a9ee253-2830-46a2-a46f-05f39e03e81e.png)|![image](https://user-images.githubusercontent.com/48436020/176079602-6ebe2635-e362-4f96-8be7-6740d89a87e1.png)|![image](https://user-images.githubusercontent.com/48436020/176079615-343c6f0f-6d7a-42a0-be70-694e30b385b5.png)|![image](https://user-images.githubusercontent.com/48436020/176079626-3918e7da-70fc-40db-a05c-9eede0e8dcac.png)|![image](https://user-images.githubusercontent.com/48436020/176079645-c80318c0-d04d-4d0e-866e-ca5209dbf481.png)|
| :-: | :-: | :-: | :-: | :-: |
| 이미지 확대 View | 세로 사진 | 가로 사진 | 이미지 클릭 | action sheet |

## 📝  To-do

- [x] 이미지 확대 View
  - [x] navigation 반투명
- [x] 세로/가로 이미지에 대한 resize 처리
- [x] 이미지를 touch하면 navigation과 하단 메뉴 사라짐 / 보이기
- [x] action sheet (재사용을 위한 파일 분리)
