### ISSUE TITLE
[FEAT] History UI

### ISSUE THREAD

**Issue by uujinn** [YAPP-Github/20th-iOS-Team-2-FE#54]
## 📌  Feature Issue

![스크린샷 2022-07-04 오후 4 58 55](https://user-images.githubusercontent.com/70887135/177109301-33115448-8fa4-4c2f-8fdb-86e7e1cfda09.png)

## 📝  To-do

- [x] Bottom Sheet
- [x] 내부 UI 구현
- [ ] Page 색상 처리
- [x] 화살표 버튼 클릭 시 Row 넘어가는 Animation
