### ISSUE TITLE
[FEAT] Message View UI

### ISSUE THREAD

**Issue by uujinn** [YAPP-Github/20th-iOS-Team-2-FE#60]
## 📌  Feature Issue
![스크린샷 2022-07-06 오후 10 09 22](https://user-images.githubusercontent.com/70887135/177557741-3b1a744e-4d5a-4d5a-b1c1-1378c67d2003.png)

## 📝  To-do

- [x] Bottom Sheet 처리
- [x] 1자 이상 작성 시 Button 색상 변경
- [x] 한줄씩 작성할 때마다 Height가 늘어나는 로직 처리

**Comment by uujinn** [comment]
내일부터 구현해보겠습니다 🤓
