### ISSUE TITLE
[FIX] 버그 체크

### ISSUE THREAD

**Issue by uujinn** [YAPP-Github/20th-iOS-Team-2-FE#61]
## 📌  Feature Issue

- [ ] 배포 전 한번 더 체크해야할 버그 목록

## 📝  To-do

- [ ] Event Row 삭제 시 (1개 -> 0개일 때) 전체 List 버벅임
- [ ] MessageView 3줄까지 'Enter'와 'Text' 입력 간 서로 Height 미세하게 안맞는 부분
