### ISSUE TITLE
[CHORE] Authorization Alert와 Navigation Bar

### ISSUE THREAD

**Issue by GeonHyeongKim** [YAPP-Github/20th-iOS-Team-2-FE#77]
## 📌  Feature Issue

- Navigation 색상 버그
- UI/UX를 위한 Authorization alert 개발
- Json Mockup

## 📝  To-do

- [ ] [개발] (앨범, 카메라, 녹음) 권한 요청 거절 후, 화면 닫기
- [ ] [버그] NavigationLink로 접근후, dismiss하면 navigation bar background color에 색상 오류
- [ ] [개발] Navigation Slide gesture로 뒤로가기
- [ ] [개발] JSON으로 MockUp 받아오기
