### ISSUE TITLE
[CHORE] Login View Detail

### ISSUE THREAD

**Issue by uujinn** [YAPP-Github/20th-iOS-Team-2-FE#79]
## 📌  Feature Issue

- [ ] Login View UI Detail
- [ ] Login 로직 재확인

## 📝  To-do

- [x]  HyperLink Text
- [ ] Lottie File 변경
---
- [ ] 카카오 로그인 재확인
- [ ] 애플 로그인 재확인
