### ISSUE TITLE
[CHORE] Home View Detail

### ISSUE THREAD

**Issue by uujinn** [YAPP-Github/20th-iOS-Team-2-FE#80]
## 📌  Feature Issue

- [x] 일정 & 채팅 UI Detail

## 📝  To-do

- [x] Event Button Row Task
---
- [x] Event Row UI
- [x] Event 전부 삭제 시 렉 발생?
- [x] Chat Row UI
- [x] Emoji View UI
