### ISSUE TITLE
[FEAT] 날짜 UI (사진 & 녹음 올리기, 날짜 수정)

### ISSUE THREAD

**Issue by GeonHyeongKim** [YAPP-Github/20th-iOS-Team-2-FE#99]
## 📌  Feature Issue

|<img width="342" alt="image" src="https://user-images.githubusercontent.com/48436020/179344399-dbb1116b-f47b-49a8-9d85-b57301d4489e.png">|<img width="344" alt="image" src="https://user-images.githubusercontent.com/48436020/179344413-feab2253-629e-485d-9ca4-f4531ec89b3f.png">|
|:-:|:-:|
|날짜 수정|올리기|

## 📝  To-do

- [x] GeneralDatePickerView UI 사용하여 옮기기
- [x] 수정 View는 따로 만들기
- [x] 사진/녹음일떄 case 구분하기
